# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
  
variables:
  - group: Docker Hub credentials

stages:
  - stage: Dockerize

    displayName: Build and push stage
    jobs:
      - job: Dockerize
        displayName: Build
        steps:
          - script:
              docker login -u $(username) -p $(password) docker.io
            displayName: Login
          - script:
              echo VERSION=$(Build.BuildNumber) > .env
            displayName: Setting enviroment
          - script: |
              cat .env
              docker compose config
            displayName: Debug
          - script:
              docker compose up -d
            displayName: Build
          - script:
              docker push lewispeace/lift-buddy:apiV$(Build.BuildNumber)
            displayName: Push api
          - script:
              docker push lewispeace/lift-buddy:uiV$(Build.BuildNumber)
            displayName: Push ui