version: '3.4'

services:
  lift.buddy.api:
    environment:
      - VERSION=${VERSION}
    image: lewispeace/lift-buddy:apiV${VERSION}
    container_name: API
    build:
      context: .
      dockerfile: Lift.Buddy.Api/Dockerfile
    ports:
      - 5200:5200
  # Try implementing build also for UI 
  lift.buddy.ui:
    image: lewispeace/lift-buddy:uiV${VERSION}
    container_name: UI
    build:
      context: Lift.Buddy.UI/ClientApp
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 80:80
